# Project information
site_name: "taddbindas.com"
site_description: "my website"
site_author: "taddyb"
site_url: "https://taddbindas.github.io"

# Copyright
copyright: "&copy; 2023 taddyb"

# Repository
repo_name: "My GitHub Profile"
repo_url: "https://github.com/taddyb"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "blue"
    accent: "blue"
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/taddyb"
    - icon: "fontawesome/brands/twitter"
      link: "https://x.com/taddyb33"

# Page tree
nav:
  - "Home": "index.md"
  - "Material for MkDocs": "material-for-mkdocs.md"
  - "Getting started":
      - "Download boilerplate": "getting-started/download-boilerplate.md"
      - "pipenv": "getting-started/pipenv.md"
      - "invoke": "getting-started/invoke.md"
      - "Docker": "getting-started/docker.md"
      - "pip": "getting-started/pip.md"
  - "Hosting and Deployment":
      - "Combinations": "hosting-and-deployment/combinations.md"
      - "Netlify": "hosting-and-deployment/netlify.md"
      - "GitHub Pages": "hosting-and-deployment/github-pages.md"
      - "GitLab Pages": "hosting-and-deployment/gitlab-pages.md"
      - "AWS Amplify Console": "hosting-and-deployment/aws-amplify-console.md"
  - "Extensions":
      - "MathJax": "extensions/mathjax.md"
      - "Code Hilite": "extensions/code-hilite.md"
      - "Footnote": "extensions/footnote.md"
  - "License": "license.md"
